# Generated by Django 3.2.9 on 2021-11-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211119_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='checkpw',
        ),
    ]
