# Generated by Django 3.2.9 on 2021-11-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_checkpw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkpw',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
