# Generated by Django 3.2.9 on 2021-11-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211119_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='checkpw',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
