# Generated by Django 3.2.9 on 2021-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='audio',
            field=models.FileField(blank=True, upload_to='audios/%Y/%m/%d/'),
        ),
    ]
