# Generated by Django 3.2.9 on 2021-11-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minu', '0002_review_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
