# Generated by Django 3.2.9 on 2021-11-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minu', '0003_auto_20211118_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='users_in',
        ),
        migrations.AddField(
            model_name='review',
            name='usersin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
