# Generated by Django 3.2.9 on 2021-11-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minu', '0004_auto_20211122_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='usersin',
            new_name='peoples',
        ),
    ]
