# Generated by Django 3.2.9 on 2021-11-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minu', '0005_rename_usersin_review_peoples'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='peoples',
            new_name='users_in',
        ),
    ]
